# fly.toml app configuration file generated for rumin-ai on 2023-08-15T14:58:49+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rumin-ai"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"



[build]

[env]
  SKIP_ENV_VALIDATION = "true"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
